#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "snac"
name = "snac2"
description.en = "A simple, minimalistic ActivityPub instance (Fediverse) with a file-based storage system"
description.fr = "Une instance ActivityPub simple et minimaliste (Fediverse) avec un stockage basé sur des fichiers"

version = "2.90~ynh1"

maintainers = ["rochacbruno"]

[upstream]
license = "MIT"
code = "https://codeberg.org/grunfink/snac2"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "100M"
ram.build = "256M"
ram.runtime = "64M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.admin]
    ask.en = "Choose the snac2 admin username"
    ask.fr = "Choisissez le nom d'utilisateur admin de snac2"
    help.en = "This will be the first user created on the instance."
    help.fr = "Ce sera le premier utilisateur créé sur l'instance."
    type = "string"

    [install.password]
    ask.en = "Choose the admin password"
    ask.fr = "Choisissez le mot de passe admin"
    type = "password"

    [install.admin_email]
    ask.en = "Admin email address (optional)"
    ask.fr = "Adresse email de l'administrateur (optionnel)"
    type = "string"
    optional = true
    default = ""

    [install.title]
    ask.en = "Instance title (optional)"
    ask.fr = "Titre de l'instance (optionnel)"
    type = "string"
    optional = true
    default = "snac2"

[resources]
    [resources.sources.main]
    url = "https://codeberg.org/grunfink/snac2/archive/2.90.tar.gz"
    sha256 = "b488b8d1c6b1c1a90365f386c6d9b0527f104546b06028d6e0eb5caa88bf5588"

    autoupdate.strategy = "latest_forgejo_tag"
    autoupdate.upstream = "https://codeberg.org/grunfink/snac2"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"
    main.show_tile = false

    [resources.ports]

    [resources.apt]
    packages = "build-essential, libcurl4-openssl-dev, libssl-dev, imagemagick, ffmpeg"
