#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE SNAC2 CONFIGURATION
#=================================================
ynh_script_progression "Updating snac2 configuration..."

# Recompute path prefix with new path
compute_path_prefix
ynh_app_setting_set --key=path_prefix --value="$path_prefix"

# Regenerate server.json with new domain/path
ynh_config_add --template="server.json" --destination="$data_dir/server.json"
chmod 600 "$data_dir/server.json"
chown "$app:$app" "$data_dir/server.json"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
